export const

  CHANGE_REGISTRATION_FORM = 'CHANGE_REGISTRATION_FORM',

  POST_REGISTRATION_FORM = 'POST_REGISTRATION_FORM',
  POST_REGISTRATION_FORM_CANCELED = 'POST_REGISTRATION_FORM_CANCELED',
  POST_REGISTRATION_FORM_RESOLVED = 'POST_REGISTRATION_FORM_RESOLVED',
  POST_REGISTRATION_FORM_REJECTED = 'POST_REGISTRATION_FORM_REJECTED',

  FETCH_IP = 'FETCH_IP',
  FETCH_IP_CANCELED = 'FETCH_IP_CANCELED',
  FETCH_IP_RESOLVED = 'FETCH_IP_RESOLVED',
  FETCH_IP_REJECTED = 'FETCH_IP_REJECTED',

  FETCH_USER = 'FETCH_USER',

  POST_MESSAGE = 'POST_MESSAGE',
  FETCH_MESSAGES = 'FETCH_MESSAGES',
  FETCH_MESSAGES_RESOLVED = 'FETCH_MESSAGES_RESOLVED',
  FETCH_MESSAGES_REJECTED = 'FETCH_MESSAGES_REJECTED',
  FETCH_MESSAGES_CANCELED = 'FETCH_MESSAGES_CANCELED'
